In [1]:
import pandas as pd
p2=pd.DataFrame(pd.read_csv(r'perovskite-ion.csv'))
p2=pd.DataFrame(p2.iloc[:,0])
p2.to_csv('p2.csv')
p2

             Name
0    LiNaPbFClBrI
1     KRbGeFClBrI
2    RbCsSnFClBrI
3     RbCsGeFFClI
4    LiNaGeFClBrI
5    LiNaSnFClBrI
6    RbCsGeFClBrI
7     RbCsSnFFBrI
8     NaKGeFClBrI
9     NaKSnFClBrI
10    KRbGeFClBrI
11    KRbSnFClBrI
12   LiCsGeFClBrI
13   LiCsSnFClBrI
14  LiCsGeBrBrBrI
15   LiCsGeFClBrI

In [2]:
import pandas as pd
p3=pd.DataFrame(pd.read_csv(r'perovskite-ion.csv'))
p3=pd.DataFrame(p3.iloc[:,1])
p3.to_csv('p3.csv')
p3

     Ion
0    Li+
1   Zn2+
2     K+
3    Na+
4   Al3+
5   Ca2+
6   Mg2+
7     F-
8    Li+
9   Zn2+
10    K+
11   Na+
12  Al3+
13  Ca2+
14  Mg2+
15    F-

In [3]:
mats = p2.iloc[:,0].values.tolist()
mats

import re

def tokenize_formula(formula):
    return re.findall('[A-Z][a-z]?|\d+|.', formula)



df1=pd.DataFrame()

# for formula in mats:
#     print("\t", tokenize_formula(formula))
#     # df2=df1.append(pd.DataFrame({'code':[formula]}),ignore_index=True)
import warnings
warnings.filterwarnings("ignore")

for formula in mats:
    tokenized = tokenize_formula(formula)
    df1 = df1.append({'Formula': formula, 'Tokenized_Formula': tokenized}, ignore_index=True)
    
# 使用 pd.Series() 将列表拆分成不同的列
df_elements1 = df1['Tokenized_Formula'].apply(pd.Series)

# 重命名列名
df_elements1.columns = [f'Element_{i+1}' for i in range(df_elements1.shape[1])]

# 合并到原始 DataFrame
df6 = pd.concat([df1, df_elements1], axis=1)
df6

,Formula,Tokenized_Formula,Element_1,Element_2,Element_3,Element_4,Element_5,Element_6,Element_7
0,LiNaPbFClBrI,"[Li, Na, Pb, F, Cl, Br, I]",Li,Na,Pb,F,Cl,Br,I
1,KRbGeFClBrI,"[K, Rb, Ge, F, Cl, Br, I]",K,Rb,Ge,F,Cl,Br,I
2,RbCsSnFClBrI,"[Rb, Cs, Sn, F, Cl, Br, I]",Rb,Cs,Sn,F,Cl,Br,I
3,RbCsGeFFClI,"[Rb, Cs, Ge, F, F, Cl, I]",Rb,Cs,Ge,F,F,Cl,I
4,LiNaGeFClBrI,"[Li, Na, Ge, F, Cl, Br, I]",Li,Na,Ge,F,Cl,Br,I
5,LiNaSnFClBrI,"[Li, Na, Sn, F, Cl, Br, I]",Li,Na,Sn,F,Cl,Br,I
6,RbCsGeFClBrI,"[Rb, Cs, Ge, F, Cl, Br, I]",Rb,Cs,Ge,F,Cl,Br,I
7,RbCsSnFFBrI,"[Rb, Cs, Sn, F, F, Br, I]",Rb,Cs,Sn,F,F,Br,I
8,NaKGeFClBrI,"[Na, K, Ge, F, Cl, Br, I]",Na,K,Ge,F,Cl,Br,I
9,NaKSnFClBrI,"[Na, K, Sn, F, Cl, Br, I]",Na,K,Sn,F,Cl,Br,I
10,KRbGeFClBrI,"[K, Rb, Ge, F, Cl, Br, I]",K,Rb,Ge,F,Cl,Br,I
11,KRbSnFClBrI,"[K, Rb, Sn, F, Cl, Br, I]",K,Rb,Sn,F,Cl,Br,I
12,LiCsGeFClBrI,"[Li, Cs, Ge, F, Cl, Br, I]",Li,Cs,Ge,F,Cl,Br,I
13,LiCsSnFClBrI,"[Li, Cs, Sn, F, Cl, Br, I]",Li,Cs,Sn,F,Cl,Br,I
14,LiCsGeBrBrBrI,"[Li, Cs, Ge, Br, Br, Br, I]",Li,Cs,Ge,Br,Br,Br,I
15,LiCsGeFClBrI,"[Li, Cs, Ge, F, Cl, Br, I]",Li,Cs,Ge,F,Cl,Br,I

In [15]:
df7=pd.DataFrame(df6.iloc[:,-7:-1])
df7

   Element_1 Element_2 Element_3 Element_4 Element_5 Element_6
0         Li        Na        Pb         F        Cl        Br
1          K        Rb        Ge         F        Cl        Br
2         Rb        Cs        Sn         F        Cl        Br
3         Rb        Cs        Ge         F         F        Cl
4         Li        Na        Ge         F        Cl        Br
5         Li        Na        Sn         F        Cl        Br
6         Rb        Cs        Ge         F        Cl        Br
7         Rb        Cs        Sn         F         F        Br
8         Na         K        Ge         F        Cl        Br
9         Na         K        Sn         F        Cl        Br
10         K        Rb        Ge         F        Cl        Br
11         K        Rb        Sn         F        Cl        Br
12        Li        Cs        Ge         F        Cl        Br
13        Li        Cs        Sn         F        Cl        Br
14        Li        Cs        Ge        Br        Br        Br
15        Li        Cs        Ge         F        Cl        Br

In [27]:
ions = p3.iloc[:,0].values.tolist()
ions

import re

def tokenize_formula(formula):
    return re.findall('[A-Z][a-z]?|\d+|.', formula)



df3=pd.DataFrame()

# for formula in mats:
#     print("\t", tokenize_formula(formula))
#     # df2=df1.append(pd.DataFrame({'code':[formula]}),ignore_index=True)
import warnings
warnings.filterwarnings("ignore")

for formula in ions:
    tokenized = tokenize_formula(formula)
    df3 = df3.append({'Formula': formula, 'Tokenized_Formula': tokenized}, ignore_index=True)
    
# 使用 pd.Series() 将列表拆分成不同的列
df_elements2 = df3['Tokenized_Formula'].apply(pd.Series)

df8 = pd.DataFrame(df_elements2.iloc[:,-3])
df8.columns = ['ion']
df8

   ion
0   Li
1   Zn
2    K
3   Na
4   Al
5   Ca
6   Mg
7    F
8   Li
9   Zn
10   K
11  Na
12  Al
13  Ca
14  Mg
15   F

In [28]:
df9 = pd.concat([df7, df8], axis=1)
df9

   Element_1 Element_2 Element_3 Element_4 Element_5 Element_6 ion
0         Li        Na        Pb         F        Cl        Br  Li
1          K        Rb        Ge         F        Cl        Br  Zn
2         Rb        Cs        Sn         F        Cl        Br   K
3         Rb        Cs        Ge         F         F        Cl  Na
4         Li        Na        Ge         F        Cl        Br  Al
5         Li        Na        Sn         F        Cl        Br  Ca
6         Rb        Cs        Ge         F        Cl        Br  Mg
7         Rb        Cs        Sn         F         F        Br   F
8         Na         K        Ge         F        Cl        Br  Li
9         Na         K        Sn         F        Cl        Br  Zn
10         K        Rb        Ge         F        Cl        Br   K
11         K        Rb        Sn         F        Cl        Br  Na
12        Li        Cs        Ge         F        Cl        Br  Al
13        Li        Cs        Sn         F        Cl        Br  Ca
14        Li        Cs        Ge        Br        Br        Br  Mg
15        Li        Cs        Ge         F        Cl        Br   F

In [29]:
import matminer
from matminer.featurizers.conversions import StrToComposition
from matminer.featurizers.composition import ElementProperty
import pandas as pd

str_to_comp = StrToComposition(target_col_id='composition')
df_comp = str_to_comp.featurize_dataframe(p2, col_id='Name')

from matminer.featurizers.composition.orbital import AtomicOrbitals
comp_to_Orbital = AtomicOrbitals()
AtomicOrbitals = comp_to_Orbital.featurize_dataframe(df_comp,col_id='composition')
AtomicOrbitals = AtomicOrbitals.iloc[:,[4,7,8]]   # data.iloc[ : , [1,2,3] ]  取所有行和第1,2,3列交叉的所有的数据
AtomicOrbitals.to_csv('1_AtomicOrbitals.csv')
AtomicOrbitals

StrToComposition:   0%|          | 0/16 [00:00<?, ?it/s]

AtomicOrbitals:   0%|          | 0/16 [00:00<?, ?it/s]

    HOMO_energy  LUMO_energy    gap_AO
0     -0.267904    -0.141831  0.126073
1     -0.267904    -0.149882  0.118022
2     -0.267904    -0.144450  0.123454
3     -0.267904    -0.149882  0.118022
4     -0.267904    -0.149882  0.118022
5     -0.267904    -0.144450  0.123454
6     -0.267904    -0.149882  0.118022
7     -0.267904    -0.144450  0.123454
8     -0.267904    -0.149882  0.118022
9     -0.267904    -0.144450  0.123454
10    -0.267904    -0.149882  0.118022
11    -0.267904    -0.144450  0.123454
12    -0.267904    -0.149882  0.118022
13    -0.267904    -0.144450  0.123454
14    -0.267904    -0.149882  0.118022
15    -0.267904    -0.149882  0.118022

In [ ]:
import logging
import gensim
from gensim.models import word2vec, KeyedVectors
import pandas as pd
import nltk
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
# from chemdataextractor import Document
# import pkuseg
import numpy as np
from nltk.tokenize import MWETokenizer
import itertools
from gensim.models import KeyedVectors
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence
from sklearn.manifold import TSNE


ele=df7
ele


model = KeyedVectors.load_word2vec_format('million.txt')




def cos(x):
    return model.similarity(x, 'battery')
# 对DataFrame中的每个元素应用这个函数
battery = ele.applymap(cos)
battery = battery.add_prefix('battery_')
# 打印处理后的DataFrame
battery.to_csv('battery.csv')
battery


def cos(x):
    return model.similarity(x, 'stable')
# 对DataFrame中的每个元素应用这个函数
stable = ele.applymap(cos)
stable = stable.add_prefix('stable_')
# 打印处理后的DataFrame
stable.to_csv('stable.csv')
stable

def cos(x):
    return model.similarity(x, 'unstable')
# 对DataFrame中的每个元素应用这个函数
unstable = ele.applymap(cos)
unstable = unstable.add_prefix('unstable_')
# 打印处理后的DataFrame
unstable.to_csv('unstable.csv')
unstable

def cos(x):
    return model.similarity(x, 'solar')
# 对DataFrame中的每个元素应用这个函数
solar = ele.applymap(cos)
solar = solar.add_prefix('solar_')
# 打印处理后的DataFrame
solar.to_csv('solar.csv')
solar

def cos(x):
    return model.similarity(x, 'photo')
# 对DataFrame中的每个元素应用这个函数
photo = ele.applymap(cos)
photo = photo.add_prefix('photo_')
# 打印处理后的DataFrame
photo.to_csv('photo.csv')
photo

def cos(x):
    return model.similarity(x, 'rechargeable')
# 对DataFrame中的每个元素应用这个函数
rechargeable = ele.applymap(cos)
rechargeable = rechargeable.add_prefix('rechargeable_')
# 打印处理后的DataFrame
rechargeable.to_csv('rechargeable.csv')
rechargeable

def cos(x):
    return model.similarity(x, 'adsorption')
# 对DataFrame中的每个元素应用这个函数
adsorption = ele.applymap(cos)
adsorption = adsorption.add_prefix('adsorption_')
# 打印处理后的DataFrame
adsorption.to_csv('adsorption.csv')
adsorption

def cos(x):
    return model.similarity(x, 'diffusion')
# 对DataFrame中的每个元素应用这个函数
diffusion = ele.applymap(cos)
diffusion = diffusion.add_prefix('diffusion_')
# 打印处理后的DataFrame
diffusion.to_csv('diffusion.csv')
diffusion

def cos(x):
    return model.similarity(x, 'intercalation')
# 对DataFrame中的每个元素应用这个函数
intercalation = ele.applymap(cos)
intercalation = intercalation.add_prefix('intercalation_')
# 打印处理后的DataFrame
intercalation.to_csv('intercalation.csv')
intercalation

NLP = pd.concat([battery, stable, unstable, solar, photo,rechargeable, adsorption, diffusion, intercalation], axis=1)
NLP.to_csv('2_NLP.csv')
NLP